apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kabinkumar/myapp.git
    targetRevision: master
    path: k8s-manifests  # Path inside your repo where Kubernetes YAML files are stored
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true  # Remove old resources not in Git
      selfHeal: true  # Auto-sync if drift detected
    syncOptions:
      - CreateNamespace=true
